### ISSUE TITLE
Swift3 branch not able to download using cocoapods

### ISSUE THREAD

**Issue by yogesh-nykaa** [soffes/Mixpanel#8]
Hi I have used below settings to download the swift3 branch using cocoapods.

`pod 'Mixpanel',`
`:git => 'https://github.com/soffes/Mixpanel.git',`
`:branch => 'swift3'`

And I am receiving the below error while using pod install command

`[!] Unable to find a specification for 'Mixpanel'.`

What changes we need to implement in Podfile so Mixpanel library can be downloaded.

**Comment by soffes** [comment]
This library doesn't have a pod spec. Feel free to PR one
